FROM centos:centos7

COPY ./libs/libfaketime /home/libfaketime

RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
    yum -y install gcc gcc-c++ make autoconf && \

    cd /home/libfaketime && make && make install && \
    touch /etc/faketimerc && \

    yum -y remove gcc gcc-c++ make autoconf && \

    yum clean all && \
    rm -rf /var/cache/yum/* /home/libfaketime

ENV FAKETIME_XRESET=1
ENV LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1
ENV FAKETIME_NO_CACHE=1